#!/usr/bin/env bash

set -uexo pipefail

# Files

cp -arfT files/etc /etc
cp -arfT files/usr /usr

# Packages

dnf -y install \
    xiaomi-pipa-firmware \
    qbootctl \
    pipa-dracut \
    pipa-sound-conf \
    bootmac \
    plymouth-plugin-script \
    https://github.com/alexray21/pocketblue/releases/download/21.08.26/basic-spinner-plymouth-theme-1.0-1.fc44.noarch.rpm 

# Services

systemctl enable qbootctl.service bootmac-bluetooth
systemctl enable iio-sensor-proxy-fix-boot.service iio-sensor-proxy-fix-suspend.service
systemctl enable nix.mount

# Kernel

plymouth-set-default-theme basic-spinner
mkdir -p /boot/dtb
dnf -y remove \
    kernel \
    kernel-core \
    kernel-modules \
    kernel-modules-core \
    kernel-headers
dnf -y install \
    https://github.com/alexray21/pocketblue/releases/download/21.08.26/kernel-7.1.7-8.BORE.ThinLTO.aarch64.rpm \
    https://github.com/alexray21/pocketblue/releases/download/21.08.26/kernel-core-7.1.7-8.BORE.ThinLTO.aarch64.rpm \
    https://github.com/alexray21/pocketblue/releases/download/21.08.26/kernel-devel-7.1.7-8.BORE.ThinLTO.aarch64.rpm \
    https://github.com/alexray21/pocketblue/releases/download/21.08.26/kernel-devel-matched-7.1.7-8.BORE.ThinLTO.aarch64.rpm \
    https://github.com/alexray21/pocketblue/releases/download/21.08.26/kernel-headers-pipa-7.1.7-8.BORE.ThinLTO.aarch64.rpm \
    https://github.com/alexray21/pocketblue/releases/download/21.08.26/kernel-modules-7.1.7-8.BORE.ThinLTO.aarch64.rpm \
    https://github.com/alexray21/pocketblue/releases/download/21.08.26/missingsymlink-0.1-0.1.noarch.rpm
rm -r /boot/dtb
