#!/usr/bin/env bash

set -uexo pipefail

# Files

cp -arfT files/etc /etc
cp -arfT files/usr /usr

# Packages

dnf -y install \
    xiaomi-pipa-firmware \
    qbootctl \
    pipa-dracut \
    pipa-sound-conf \
    bootmac \
    plymouth-plugin-script \
    https://github.com/alexray21/pocketblue/releases/download/1/basic-spinner-plymouth-theme-1.0-1.fc44.noarch.rpm \
    acpid evtest glibc-langpack-ru hexagonrpc pipa-sensors iio-sensor-proxy libssc waydroid

dnf -y remove \
    qemu-user-static-x86 \
    qemu-guest-agent

# Services

systemctl enable qbootctl.service bootmac-bluetooth
systemctl enable iio-sensor-proxy-fix-boot.service iio-sensor-proxy-fix-suspend.service
systemctl enable nix.mount
systemctl enable swclock-offset-boot.service swclock-offset-shutdown.service

# Kernel

plymouth-set-default-theme basic-spinner
mkdir -p /boot/dtb
dnf -y remove \
    kernel \
    kernel-core \
    kernel-modules \
    kernel-modules-core \
    kernel-headers
dnf -y install \
    https://github.com/alexray21/pocketblue/releases/download/1/kernel-core.rpm \
    https://github.com/alexray21/pocketblue/releases/download/1/kernel-devel-matched.rpm \
    https://github.com/alexray21/pocketblue/releases/download/1/kernel-devel.rpm \
    https://github.com/alexray21/pocketblue/releases/download/1/kernel-headers-pipa.rpm \
    https://github.com/alexray21/pocketblue/releases/download/1/kernel-modules.rpm \
    https://github.com/alexray21/pocketblue/releases/download/1/kernel.rpm \
    https://github.com/alexray21/pocketblue/releases/download/1/missingsymlink-0.1-0.1.noarch.rpm
rm -r /boot/dtb
